[package]
name = "rust-book-exercises"
version = "0.1.0"
authors = ["Zakkary Verrilli <zakkaryv@gmail.com>"]
edition = "2018"

[dependencies]
termion = "*"

[lib]
name = "lib"
path = "src/lib/lib.rs"
